WebBanDienThoai/Models/Voucher.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.Customer = new HashSet<Customer>();
            this.Order = new HashSet<Order>();
        }

        public int IdVoucher { get; set; }
        [Display(Name = "Ảnh voucher")]
        public string Images { get; set; }
        [Display(Name = "Ngày áp dụng")]
        public Nullable<System.DateTime> DateStart { get; set; }
        [Display(Name = "Ngày kết thúc")]
        public Nullable<System.DateTime> DateEnd { get; set; }

        [DisplayFormat(DataFormatString = "{0:0,0₫}")]
        [Display(Name = "Giá sản phẩm")]
        public Nullable<decimal> Price { get; set; }
        [Display(Name = "Trạng Thái")]
        public Nullable<bool> Status { get; set; }
        [Display(Name = "Tên voucher")]
        [Required(ErrorMessage = "Tên voucher Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "Tên voucher Không Được Vượt Quá 250 Kí Tự")]
        public string NameVoucher { get; set; }
        [Display(Name = "Mô tả ngắn")]
        [AllowHtml]
        public string DescriptShort { get; set; }
        [AllowHtml]
        [Column(TypeName = "ntext")]
        [Display(Name = "Nội Dung")]
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        [Display(Name = "Mã voucher")]
        [Required(ErrorMessage = "Mã voucher Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "Tên voucher Không Được Vượt Quá 250 Kí Tự")]
        public string Code { get; set; }
        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "Số Lượng Không Được Bỏ Trống")]
        public int Quanlity { get; set; }
        public string Author { get; set; }
        [Display(Name = "Đường Dẫn URL")]
        [Required(ErrorMessage = "URL Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "URL Không Được Vượt Quá 250 Kí Tự")]
        [Index(IsUnique = true)]
        [Column(TypeName = "varchar")]
        public string Alias { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}

WebBanDienThoai/Controllers/VoucherController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanDienThoai.Models;
namespace WebBanDienThoai.Controllers
{
    public class VoucherController : Controller
    {
        // GET: Voucher
        private WebMobileEntities db = new WebMobileEntities();
        public ActionResult Index(int? page, string q)
        {
            var count_voucher = (from cate in db.Voucher select cate.IdVoucher).Count();

            ViewBag.count_cate = count_voucher;




            var model = from p in db.Voucher orderby p.CreatedAt descending select p;
            int pagesize = 15;
            int pageNumber = (page ?? 1);


            if (!string.IsNullOrEmpty(q))
            {
                model = model.Where(x => x.NameVoucher.Contains(q)).OrderByDescending(x => x.CreatedAt);
            }

            ViewBag.keyword_search = q;

            return View(model.ToPagedList(pageNumber, pagesize));
        }
        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Voucher voucher, bool status_mi, HttpPostedFileBase image_avatar)
        {
            if (ModelState.IsValid)
            {


                bool tus;
                if (status_mi == true)
                {
                    tus = true;
                }
                else
                {
                    tus = false;
                }

                voucher.Author = Session["Username"].ToString();
                voucher.CreatedAt = DateTime.Now;
                voucher.Status = tus;


                var check_name = db.Voucher.Count(x => x.NameVoucher == voucher.NameVoucher);
                var check_alias = db.Voucher.Count(x => x.Alias == voucher.Alias);
                if (check_name > 0)
                {
                    ViewBag.check_name = "Tên Sản Phẩm  Đã Tồn Tại";
                }
                else if (check_alias > 0)
                {
                    ViewBag.check_alias = "Đường Dẫn URL Đã Tồn Tại";
                }
                else
                {

                    if (image_avatar != null)
                    {
                        var filename = Path.GetFileName(image_avatar.FileName);
                        var path = Path.Combine(Server.MapPath("~/Upload/Images"), filename);


                        image_avatar.SaveAs(path);
                        voucher.Images = "/Upload/Images/" + image_avatar.FileName;
                    }
                    else
                    {
                        voucher.Images = "";
                    }

                    db.Voucher.Add(voucher);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }

            
            return View(voucher);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voucher Voucher = db.Voucher.Find(id);
            if (Voucher == null)
            {
                return HttpNotFound();
            }
           
            return View(Voucher);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Voucher voucher, HttpPostedFileBase image_avatars)
        {
            if (ModelState.IsValid)
            {


                if (image_avatars != null)
                {
                    var filename = Path.GetFileName(image_avatars.FileName);
                    var path = Path.Combine(Server.MapPath("~/Upload/Images"), filename);
                    image_avatars.SaveAs(path);
                    voucher.Images = "/Upload/Images/" + image_avatars.FileName;
                }
                else
                {
                    voucher.Images = "";
                }




                db.Entry(voucher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
          
            return View(voucher);
        }



        public ActionResult Delete(int? id)
        {

            Voucher voucher = db.Voucher.Find(id);

            if (voucher.Images != "")
            {
                var filename = Path.GetFileName(voucher.Images);
                System.IO.File.Delete(Request.PhysicalApplicationPath + "/Upload/Images/" + filename);
            }

            db.Voucher.Remove(voucher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanDienThoai/Views/Voucher/Create.cshtml
@model WebBanDienThoai.Models.Voucher

@{
    ViewBag.Title = "Tạo Mới nhóm sản phẩm";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (Convert.ToInt32(Session["role"].ToString()) == 1)
{
    <div class="curd" style="margin-right:70px;width:100%;">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <div class="breadcrumb">
                    <div class="breadcrumb-left">
                        <i class="menu-icon fa fa-user" aria-hidden="true"></i>
                        <a href="~/Admin/Users" class="title_bread"> Danh sách nhóm sản phẩm</a>
                        <span style="color:#ccc;margin:0px 15px;font-size:20px;"> /</span>
                        <span class="title_bread"> Thêm Mới</span>
                    </div>
                    <div class="breadcrumb-add">
                        @Html.ActionLink("Hủy", "Index", "", new { @class = "btn btn-default" })
                        <input type="submit" value="Lưu Lại" class="btn btn-primary" />
                    </div>
                </div><!-- /.breadcrumb -->


            </div>

            <div class="createandedit">

                <div class="row">

                    @Html.AntiForgeryToken()


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <p style="color:red;font-weight:bold;text-align:center;">@ViewBag.check_cate</p>
                    <p style="color:red;font-weight:bold;text-align:center;">@ViewBag.check_alias</p>
                    <div class="col-xs-12 col-md-8">

                        <div class="editcreate">



                            <div class="form-group">
                                @Html.LabelFor(model => model.NameVoucher, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.NameVoucher, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NameVoucher, "", new { @class = "text-danger" })
                                <span>@ViewBag.check_name</span>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })

                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.DescriptShort, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.DescriptShort, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DescriptShort, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DateStart, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.DateEnd, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.DateEnd, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DateEnd, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Quanlity, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Quanlity, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Quanlity, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label" })

                                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" }, id = "txtContent" })
                                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })

                            </div>







                        </div>









                    </div>

                    <div class="col-xs-12 col-md-4">
                        <div class="visible-status">
                            <p class="title_st">Hiển thị</p>
                            <div class="check-st">
                                <div class="show-st">
                                    <input type="radio" name="status_mi" value="true" checked /> <span class="hideshow">Hiện</span>
                                </div>
                                <div class="show-st">
                                    <input type="radio" name="status_mi" value="false" /> <span class="hideshow">Ẩn</span>
                                </div>
                            </div>

                            <div class="time-stamp">
                                <p class="title_sts"> Thời Gian:</p>
                                <input type="text" value="@DateTime.Now" disabled />
                            </div>
                        </div>



                        <div class="image-avatar">
                            <p class="title_anh">Ảnh đại diện</p>

                            <div class="frame-image">
                                <div class="noset-image">
                                    <input type="file" name="image_avatar" class="hidden" id="uploadFile" onchange="readURL(this);" />
                                    <div class="select-image" onclick="performClick('uploadFile');"><i class="fa fa-picture-o" aria-hidden="true"></i><br />Chọn hình</div>
                                </div>


                                <div id="showImage">
                                    <img id="image_showed" width=auto />
                                </div>

                            </div>

                            <a href="javascript::0" class="change_image" onclick="performClick('uploadFile');">Thay hình ảnh</a>

                        </div>
                    </div>





                </div>

                <div class="text-left" style="margin-top:20px;">
                    <i class="fa fa-angle-double-left" aria-hidden="true" style="color:red !important;"></i>  @Html.ActionLink("Trở lại trang trước", "Index", "", new { style = "color:red;font-size:12px;" })
                </div>


            </div>
        }

    </div>

}
else
{
    <div id="404" class="page-not not-found bg_w">
        <div class="columns-container">
            <div class="container" id="columns">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                        <div class="img-404 text-center">
                            <img src="/Content/ShopPage/images/404.png" alt="Lỗi 404 không tìm thấy trang">
                        </div>
                        <div class="text-center"><a class="btn-outline back-to-col" href="~/AdminHome">Quay lại trang chủ</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}











<script type="text/javascript">
    function performClick(elemId) {
        var elem = document.getElementById(elemId);
        if (elem && document.createEvent) {
            var evt = document.createEvent("MouseEvents");
            evt.initEvent("click", true, false);
            elem.dispatchEvent(evt);
        }
    }
</script>




<script>
    var loadFile = function (event) {
        var files = event.target.files;
        for (var i = 0; i < files.length; i++) {
            $("#showImage").append("<img src='" + URL.createObjectURL(event.target.files[i]) + "' class='imaged' />");
        }
    }
</script>



<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            $('.noset-image').hide();
            $('.change_image').css("display", "block");
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image_showed')
                    .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>



<script>



    $("#NameVoucher").keyup(function () {
        var Text = $(this).val();
        Text = Text.toLowerCase();
        $("#Alias").val(convertToSlug(Text));
    });


    $("#NameVoucher ").mouseout(function () {
        var Text = $(this).val();
        Text = Text.toLowerCase();
        $("#Alias").val(convertToSlug(Text));
    });
</script>

WebBanDienThoai/Views/Voucher/Index.cshtml
@model PagedList.IPagedList<WebBanDienThoai.Models.Voucher>

@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách voucher";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (Convert.ToInt32(Session["role"].ToString()) == 1)
{
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <div class="breadcrumb">
            <div class="breadcrumb-left">
                <i class="menu-icon fa fa-tags" aria-hidden="true"></i>
                <span class="title_bread"> Nhóm Sản Phẩm</span>
            </div>
            <div class="breadcrumb-add">
                @Html.ActionLink("Thêm Mới", "Create")
            </div>
        </div><!-- /.breadcrumb -->


    </div>



    <div class="internew-content">
        <div class="title_cat">
            <h3>Danh sách Voucher</h3>
        </div>


        <div class="content-layout">
            <div class="pull-left">
                <p class="count">Tổng số voucher: <span>@ViewBag.count_voucher</span> | Tổng số trang:  <span>@Model.PageCount</span></p>
            </div>
            <div class="pull-right">
                <div class="border_search">
                    @using (Html.BeginForm("Index", "Voucher", FormMethod.Get))
                    {
                        <span class="next-input-add-on next-input__add-on--before">
                            <svg class="svg-next-icon svg-next-icon-size-20">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-search-reverse">
                                    <svg id="next-search-reverse" class="icon-symbol--loaded" width="100%" height="100%"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M8 12c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm9.707 4.293l-4.82-4.82C13.585 10.493 14 9.296 14 8c0-3.313-2.687-6-6-6S2 4.687 2 8s2.687 6 6 6c1.296 0 2.492-.415 3.473-1.113l4.82 4.82c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414z"></path></svg></svg>
                                </use>
                            </svg>
                        </span><input type="text" placeholder="Nhập từ khóa..." value="@ViewBag.keyword_search" name="q" /><input type="submit" class="hidden" />
                    }
                </div>
            </div>
        </div>

        <table class="table table-responsive">
            <tr>
                <th>
                    Tên Voucher
                </th>

                <th>
                    Ảnh Voucher
                </th>

                <th>
                    Mã Code
                </th>
                <th>
                    Ngày đăng
                </th>
                <th>
                    Trạng thái
                </th>
                <th>Tùy Chỉnh</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.NameVoucher)
                    </td>
                    <td>
                        <img src="@item.Images" style="width:60px;height:60px" />
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </td>
                    <td class="text-center">
                        @{
                            if (item.Status == true)
                            {
                                <p class="btn btn-success btn-xs text-center">Active</p>
                            }
                            else
                            {
                                <p class="btn btn-danger btn-xs text-center">Disible</p>
                            }
                        }
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Sửa", "Edit", new { id = item.IdVoucher }, htmlAttributes: new { @class = "view_sua btn btn-xs btn-success" })
                        @Html.ActionLink("Xóa", "Delete", new { id = item.IdVoucher }, htmlAttributes: new { @class = "btn_confirm btn btn-xs btn-danger" })
                    </td>
                </tr>
            }

        </table>
        <div class="pagination">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @q = ViewBag.keyword_search }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
        </div>

    </div>
}
else
{
    <div id="404" class="page-not not-found bg_w">
        <div class="columns-container">
            <div class="container" id="columns">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                        <div class="img-404 text-center">
                            <img src="/Content/ShopPage/images/404.png" alt="Lỗi 404 không tìm thấy trang">
                        </div>
                        <div class="text-center"><a class="btn-outline back-to-col" href="~/AdminHome">Quay lại trang chủ</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}